apiVersion: v1
kind: Pod
metadata:
  name: task
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: wiw
      image: ebensma/mkdn:latest
      volumeMounts:
        - mountPath: "/usr/share"
          name: task-pv-storage