apiVersion: v1
kind: Pod
metadata:
  name: task
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: task-pv-claim
  containers:
    - name: my-name
      image: ebensma/mkdn:latest
      volumeMounts:
        - mountPath: "/workspace"
          name: task-pv-storage
  restartPolicy: OnFailure