apiVersion: v1
kind: Pod
metadata:
  name: saver-pod
spec:
  containers:
  - name: saver-pod
    image: ubuntu
    args: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /workspace
      name: minio-pv-claim
  restartPolicy: Never
  volumes:
    - name: minio-pv-claim
      persistentVolumeClaim:
        claimName: minio-pv-claim