apiVersion: v1
kind: Pod
metadata:
  name: saver-pod
spec:
  containers:
  - name: saver-pod
    image: ubuntu
    args: ["sleep", "infinity"]
    volumeMounts:
    - mountPath: /workspace
      name: deepgtex-prp
  restartPolicy: Never
  volumes:
    - name: deepgtex-prp
      persistentVolumeClaim:
        claimName: deepgtex-prp